application:
  address: :80
database:
  scheme: youasholding
  user: youasholding
  password: Test123%
  hostname: youasholding.database.windows.net
  port: 1433
  url: postgres://zyjgextzreodlm:d14edbbaee478055a441c94b6c5c13c5b9e0fc4e3a3d5b24a4387796a2b24418@ec2-23-22-191-232.compute-1.amazonaws.com:5432/dafnb12r2vel7t
#job:
#  asset-sync:
#    cron: * 0/1 * * * *