application:
  address: :80
database:
  scheme: youasholding
  user: youasholding
  password: Test123%
  hostname: youasholding.database.windows.net
  port: 1433
  url: postgres://svwxriprmoggel:be49cb98e3865a0da0774d3df72c373152ca4a1561aeda0ca1b9724455a68621@ec2-52-0-114-209.compute-1.amazonaws.com:5432/d4pupkl4mjp541
#job:
#  asset-sync:
#    cron: * 0/1 * * * *