// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Cristiano Altmann",
            "email": "crisaltmann@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/crisaltmann/fundament-stock-api"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assets": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retorna a lista de ativos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/asset_api.AssetResponse"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Insere Ativo",
                "parameters": [
                    {
                        "description": "User-Data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/asset_api.AssetPostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": ""
                    }
                }
            }
        },
        "/assets/:asset-id/quarterly-results": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retorna a lista de resultados de ativos ativos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/asset_api.QuarterlyResultResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Insere Resultado Trimestral Ativo",
                "parameters": [
                    {
                        "description": "User-Data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/asset_api.QuarterlyResultPostRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": ""
                    }
                }
            }
        },
        "/assets/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retorna a ativo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/asset_api.AssetResponse"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "summary": "Atualiza Ativo",
                "parameters": [
                    {
                        "description": "User-Data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/asset_api.AssetPutRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/holding": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retorna Resultados holding do usuario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "usuario",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "expandir ativos",
                        "name": "expandir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/holding_api.Holdings"
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retorna a lista de ordens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/order_api.OrderGetResponse"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Insere Ordem",
                "parameters": [
                    {
                        "description": "User-Data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order_api.OrderPostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": ""
                    }
                }
            }
        },
        "/portfolio": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retorna portfolio do usuario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "usuario",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/portfolio_api.PortfolioGetResponse"
                        }
                    }
                }
            }
        },
        "/quarters": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retorna trimestres",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/quarter_api.TrimestreGetResponse"
                            }
                        }
                    }
                }
            }
        },
        "/quarters/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retorna o trimestre",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "quarter id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quarter_api.TrimestreGetResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "asset_api.AssetPostRequest": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "asset_api.AssetPutRequest": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "cotacao": {
                    "type": "number"
                },
                "logo": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "asset_api.AssetResponse": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "cotacao": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "asset_api.QuarterlyResultPostRequest": {
            "type": "object",
            "properties": {
                "divida_liquida": {
                    "type": "integer"
                },
                "ebitda": {
                    "type": "integer"
                },
                "id_ativo": {
                    "type": "integer"
                },
                "id_trimestre": {
                    "type": "integer"
                },
                "lucro_liquido": {
                    "type": "integer"
                },
                "receita_liquida": {
                    "type": "integer"
                }
            }
        },
        "asset_api.QuarterlyResultResponse": {
            "type": "object",
            "properties": {
                "divida_ebitda": {
                    "type": "number"
                },
                "divida_liquida": {
                    "type": "integer"
                },
                "ebitda": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "id_ativo": {
                    "type": "integer"
                },
                "id_trimestre": {
                    "type": "integer"
                },
                "lucro_liquido": {
                    "type": "integer"
                },
                "margem_ebitda": {
                    "type": "number"
                },
                "margem_liquida": {
                    "type": "number"
                },
                "receita_liquida": {
                    "type": "integer"
                }
            }
        },
        "holding_api.Ativo": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "holding_api.Holding": {
            "type": "object",
            "properties": {
                "ativos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/holding_api.HoldingAtivo"
                    }
                },
                "div_ebitda": {
                    "type": "number"
                },
                "divida_liquida": {
                    "type": "integer"
                },
                "ebitda": {
                    "type": "integer"
                },
                "lucro_liquido": {
                    "type": "integer"
                },
                "margem_ebitda": {
                    "type": "number"
                },
                "margem_liquida": {
                    "type": "number"
                },
                "receita_liquida": {
                    "type": "integer"
                },
                "trimestre": {
                    "$ref": "#/definitions/holding_api.Trimestre"
                }
            }
        },
        "holding_api.HoldingAtivo": {
            "type": "object",
            "properties": {
                "ativo": {
                    "$ref": "#/definitions/holding_api.Ativo"
                },
                "div_ebitda": {
                    "type": "number"
                },
                "divida_liquida": {
                    "type": "integer"
                },
                "ebitda": {
                    "type": "integer"
                },
                "id_trimestre": {
                    "type": "integer"
                },
                "lucro_liquido": {
                    "type": "integer"
                },
                "margem_ebitda": {
                    "type": "number"
                },
                "margem_liquida": {
                    "type": "number"
                },
                "receita_liquida": {
                    "type": "integer"
                }
            }
        },
        "holding_api.Holdings": {
            "type": "object",
            "properties": {
                "holdings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/holding_api.Holding"
                    }
                }
            }
        },
        "holding_api.Trimestre": {
            "type": "object",
            "properties": {
                "ano": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "trimestre": {
                    "type": "integer"
                }
            }
        },
        "order_api.OrderGetResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_ativo": {
                    "type": "integer"
                },
                "id_usuario": {
                    "type": "integer"
                },
                "quantidade": {
                    "type": "integer"
                },
                "tipo": {
                    "type": "string"
                },
                "valor": {
                    "type": "number"
                }
            }
        },
        "order_api.OrderPostRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "id_ativo": {
                    "type": "integer"
                },
                "id_usuario": {
                    "type": "integer"
                },
                "quantidade": {
                    "type": "integer"
                },
                "tipo": {
                    "type": "string"
                },
                "valor": {
                    "type": "number"
                }
            }
        },
        "portfolio_api.Ativo": {
            "type": "object",
            "properties": {
                "Total": {
                    "type": "integer"
                },
                "codigo": {
                    "type": "string"
                },
                "cotacao": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "type": "string"
                }
            }
        },
        "portfolio_api.PortfolioGetResponse": {
            "type": "object",
            "properties": {
                "ativo": {
                    "$ref": "#/definitions/portfolio_api.Ativo"
                },
                "id_usuario": {
                    "type": "integer"
                },
                "quantidade": {
                    "type": "integer"
                },
                "valor": {
                    "type": "number"
                }
            }
        },
        "quarter_api.TrimestreGetResponse": {
            "type": "object",
            "properties": {
                "ano": {
                    "type": "integer"
                },
                "codigo": {
                    "type": "string"
                },
                "data_fim": {
                    "type": "string"
                },
                "data_inicio": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "trimestre": {
                    "type": "integer"
                },
                "trimestre_anterior": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Fundament Stock Api Swagger API",
	Description: "Swagger API for Fundament Stock Api.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
