basePath: /
definitions:
  asset_api.AssetPostRequest:
    properties:
      codigo:
        type: string
      logo:
        type: string
      nome:
        type: string
      total:
        type: integer
    type: object
  asset_api.AssetPutRequest:
    properties:
      codigo:
        type: string
      cotacao:
        type: number
      logo:
        type: string
      nome:
        type: string
      total:
        type: integer
    type: object
  asset_api.AssetResponse:
    properties:
      codigo:
        type: string
      cotacao:
        type: number
      id:
        type: integer
      logo:
        type: string
      nome:
        type: string
      total:
        type: integer
    type: object
  asset_api.QuarterlyResultPostRequest:
    properties:
      divida_liquida:
        type: integer
      ebitda:
        type: integer
      id_ativo:
        type: integer
      id_trimestre:
        type: integer
      lucro_liquido:
        type: integer
      receita_liquida:
        type: integer
    type: object
  asset_api.QuarterlyResultResponse:
    properties:
      divida_ebitda:
        type: number
      divida_liquida:
        type: integer
      ebitda:
        type: integer
      id:
        type: integer
      id_ativo:
        type: integer
      id_trimestre:
        type: integer
      lucro_liquido:
        type: integer
      margem_ebitda:
        type: number
      margem_liquida:
        type: number
      receita_liquida:
        type: integer
    type: object
  holding_api.Ativo:
    properties:
      codigo:
        type: string
      id:
        type: integer
      nome:
        type: string
    type: object
  holding_api.Holding:
    properties:
      ativos:
        items:
          $ref: '#/definitions/holding_api.HoldingAtivo'
        type: array
      div_ebitda:
        type: number
      divida_liquida:
        type: integer
      ebitda:
        type: integer
      lucro_liquido:
        type: integer
      margem_ebitda:
        type: number
      margem_liquida:
        type: number
      receita_liquida:
        type: integer
      trimestre:
        $ref: '#/definitions/holding_api.Trimestre'
    type: object
  holding_api.HoldingAtivo:
    properties:
      ativo:
        $ref: '#/definitions/holding_api.Ativo'
      div_ebitda:
        type: number
      divida_liquida:
        type: integer
      ebitda:
        type: integer
      id_trimestre:
        type: integer
      lucro_liquido:
        type: integer
      margem_ebitda:
        type: number
      margem_liquida:
        type: number
      receita_liquida:
        type: integer
    type: object
  holding_api.Holdings:
    properties:
      holdings:
        items:
          $ref: '#/definitions/holding_api.Holding'
        type: array
    type: object
  holding_api.Trimestre:
    properties:
      ano:
        type: integer
      id:
        type: integer
      trimestre:
        type: integer
    type: object
  order_api.OrderGetResponse:
    properties:
      data:
        type: string
      id:
        type: integer
      id_ativo:
        type: integer
      id_usuario:
        type: integer
      quantidade:
        type: integer
      tipo:
        type: string
      valor:
        type: number
    type: object
  order_api.OrderPostRequest:
    properties:
      data:
        type: string
      id_ativo:
        type: integer
      id_usuario:
        type: integer
      quantidade:
        type: integer
      tipo:
        type: string
      valor:
        type: number
    type: object
  portfolio_api.Ativo:
    properties:
      Total:
        type: integer
      codigo:
        type: string
      cotacao:
        type: number
      id:
        type: integer
      logo:
        type: string
    type: object
  portfolio_api.PortfolioGetResponse:
    properties:
      ativo:
        $ref: '#/definitions/portfolio_api.Ativo'
      id_usuario:
        type: integer
      quantidade:
        type: integer
      valor:
        type: number
    type: object
  quarter_api.TrimestreGetResponse:
    properties:
      ano:
        type: integer
      codigo:
        type: string
      data_fim:
        type: string
      data_inicio:
        type: string
      id:
        type: integer
      trimestre:
        type: integer
      trimestre_anterior:
        type: integer
    type: object
info:
  contact:
    email: crisaltmann@gmail.com
    name: Cristiano Altmann
  description: Swagger API for Fundament Stock Api.
  license:
    name: MIT
    url: https://github.com/crisaltmann/fundament-stock-api
  termsOfService: http://swagger.io/terms/
  title: Fundament Stock Api Swagger API
  version: "1.0"
paths:
  /assets:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/asset_api.AssetResponse'
      summary: Retorna a lista de ativos
    post:
      parameters:
      - description: User-Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/asset_api.AssetPostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ""
      summary: Insere Ativo
  /assets/:asset-id/quarterly-results:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/asset_api.QuarterlyResultResponse'
            type: array
      summary: Retorna a lista de resultados de ativos ativos
    post:
      parameters:
      - description: User-Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/asset_api.QuarterlyResultPostRequest'
      - description: Asset ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: ""
      summary: Insere Resultado Trimestral Ativo
  /assets/{id}:
    get:
      parameters:
      - description: Asset ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/asset_api.AssetResponse'
      summary: Retorna a ativo
    put:
      parameters:
      - description: User-Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/asset_api.AssetPutRequest'
      - description: Asset ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Atualiza Ativo
  /holding:
    get:
      parameters:
      - description: user id
        in: query
        name: usuario
        required: true
        type: string
      - description: expandir ativos
        in: query
        name: expandir
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/holding_api.Holdings'
      summary: Retorna Resultados holding do usuario
  /orders:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order_api.OrderGetResponse'
      summary: Retorna a lista de ordens
    post:
      parameters:
      - description: User-Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/order_api.OrderPostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ""
      summary: Insere Ordem
  /portfolio:
    get:
      parameters:
      - description: user id
        in: query
        name: usuario
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/portfolio_api.PortfolioGetResponse'
      summary: Retorna portfolio do usuario
  /quarters:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/quarter_api.TrimestreGetResponse'
            type: array
      summary: Retorna trimestres
  /quarters/{id}:
    get:
      parameters:
      - description: quarter id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/quarter_api.TrimestreGetResponse'
      summary: Retorna o trimestre
swagger: "2.0"
